language: python
sudo: false
env:
  matrix:
    - TOXENV=py27-dj18-postgres
    - TOXENV=py27-dj18-mysql
    - TOXENV=py27-dj19-postgres
    - TOXENV=py27-dj19-mysql
    - TOXENV=py27-dj110-postgres
    - TOXENV=py27-dj110-mysql

    - TOXENV=py34-dj18-postgres
    - TOXENV=py34-dj18-mysql
    - TOXENV=py34-dj19-postgres
    - TOXENV=py34-dj19-mysql
    - TOXENV=py34-dj110-postgres
    - TOXENV=py34-dj110-mysql

    - TOXENV=py35-dj18-postgres
    - TOXENV=py35-dj18-mysql
    - TOXENV=py35-dj19-postgres
    - TOXENV=py35-dj19-mysql
    - TOXENV=py35-dj110-postgres
    - TOXENV=py35-dj110-mysql
install:
  - pip install tox
script: tox
